# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_hub import service_pb2 as grpc__hub_dot_service__pb2


class SimpleServiceStub(object):
    """some SimpleService description
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/SimpleService/Ping',
                request_serializer=grpc__hub_dot_service__pb2.PingMessage.SerializeToString,
                response_deserializer=grpc__hub_dot_service__pb2.PingMessage.FromString,
                )


class SimpleServiceServicer(object):
    """some SimpleService description
    """

    def Ping(self, request, context):
        """Ping rpc description
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=grpc__hub_dot_service__pb2.PingMessage.FromString,
                    response_serializer=grpc__hub_dot_service__pb2.PingMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimpleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleService(object):
    """some SimpleService description
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimpleService/Ping',
            grpc__hub_dot_service__pb2.PingMessage.SerializeToString,
            grpc__hub_dot_service__pb2.PingMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
