# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_hub/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16grpc_hub/service.proto\"\x1b\n\x0bPingMessage\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t25\n\rSimpleService\x12$\n\x04Ping\x12\x0c.PingMessage\x1a\x0c.PingMessage\"\x00\x42\x1eZ\x1c\x65xample.com/project/grpc_hubb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_hub.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\034example.com/project/grpc_hub'
  _globals['_PINGMESSAGE']._serialized_start=26
  _globals['_PINGMESSAGE']._serialized_end=53
  _globals['_SIMPLESERVICE']._serialized_start=55
  _globals['_SIMPLESERVICE']._serialized_end=108
# @@protoc_insertion_point(module_scope)
